Create CONTRIBUTING.md
opensuspect/opensuspect-legacy pull request #163
Opened 2020-11-01 10:52 UTC by monban

I want to give people an idea of how they can contribute to the project.

2020-11-01 13:46 UTC, nicemicro commented
I like the idea!
I'd suggest to add the link to the programming team's chatroom for reference. It's always nice if people drop by to say hi :)

2020-11-01 13:46 UTC, nicemicro requested changes
Please add a link to the Matrix chatroom of the programming team.

2020-11-02 09:41 UTC, GrbavaCigla approved these changes

2020-11-02 10:19 UTC, nicemicro approved these changes

2020-11-02 10:20 UTC, merged