Successful working keybinds in the games
opensuspect/opensuspect-legacy pull request #171
Opened 2020-11-08 13:05 UTC by zapzoop0099

I have Successfully created the keybinds in the games for now this is for movement only but can be added for other stuff easily please review it and the option is available in settings menu

2020-11-08 13:25 UTC, nicemicro submitted a review, later dismissed
It seems good to me, tested and it works fine.
If anyone else wants to review code quality, be my guest, I just scrolled through as far as I'm concerned it looks good.

2020-11-08 15:26 UTC, vainiovano commented
The keybind system shouldn't be that separated from the other settings. In this implementation, editing keybinds modifies the game's source directory. The keybinds should be saved with other settings in `user://settings.cfg`. If using the same settings system isn't possible, the keybinds should still be in the user directory to preserve the source code directory.

2020-11-10 13:05 UTC, zapzoop0099 commented
The code is now perfect and using the same settings.cfg file of game and also saving in user home directory

2020-11-10 13:21 UTC, vainiovano requested changes

2020-11-10 13:21 UTC, vainiovano commented on src/assets/autoload/uimanager.gd
> +	write_keybinds()
The keybinds shouldn't be reset each time the game is started.

2020-11-10 13:21 UTC, vainiovano commented on src/assets/ui/submenus/settings/Keybind/KeyBind.gd
> +			label.text = "Right"
inconsistent case

2020-11-10 14:25 UTC, closed without merging

2020-11-10 14:26 UTC, zapzoop0099 commented
I have closed this pull request And will write a new one as commit to these pr are now useless