Kill Mechanics for Infiltrators (#193)
opensuspect/opensuspect-legacy pull request #203
Opened 2020-11-20 21:01 UTC by jngo102

- Added red outline to players when they are in kill range of an infiltrator
- Added kill icon that indicates cooldown between kills
- Added kill and reload input actions for infiltrators
- Check role to determine whether player should have infiltrator elements
- Renamed and changed some physics layer names (tentative names)

2020-11-20 21:53 UTC, TheSecondReal0 requested changes
Other players are visible even when out of range of the light circle, this was probably caused by the shader on the player sprite being changed. Besides this, it looks great!

2020-11-20 22:21 UTC, Poket-Jony commented
I also noticed that the infiltrator-ui does not reset itself when you go back to the lobby. In addition, the kill countdown doesn't work for me.

2020-11-20 23:09 UTC, jngo102 commented
Can you clarify what you mean by the cooldown not working?

2020-11-21 00:43 UTC, nicemicro requested changes
Please check [kill mechanics](https://github.com/opensuspect/design-document/blob/main/general_gameplay.md#kill-mechanics) and conform to the description provided there.

2020-11-21 00:43 UTC, nicemicro commented on src/assets/player/infiltrator.gd
> +onready var kill_cooldown_timer: Timer = $KillCooldownTimer
Please check the game design document on [kill mechanics](https://github.com/opensuspect/design-document/blob/main/general_gameplay.md#kill-mechanics).
While a kill cooldown is possible to be used on other maps / game modes, in the first map there is no cooldown, but a gun reloading mechanism, that is initiated by the player, but while reloading can't move and can be discovered by others.

2020-11-21 05:34 UTC, TheSecondReal0 requested changes
It works perfectly when it's run in debug mode or in the editor, but the infiltrator client always crashes when the lobby button is pressed. My best idea to fix this is to move away from constantly polling the infiltrator node and instead use signals to relay information.

2020-11-21 13:10 UTC, nicemicro submitted a review, later dismissed

2020-11-21 13:11 UTC, nicemicro commented
Is the mechanics for dying for the killed people will be implemented separately?

2020-11-21 15:26 UTC, jngo102 commented
> Is the mechanics for dying for the killed people will be implemented separately?

Yes, we should open another PR for that. I'd be willing to take on that task as well.

2020-11-21 22:24 UTC, TheSecondReal0 approved these changes
Everything works perfectly! Despite the long journey to get to this point, it's ready to merge! What a great first PR

2020-11-21 22:37 UTC, merged