Map is now syncd between server and client, custom maps are now possible.
opensuspect/opensuspect-legacy pull request #214
Opened 2020-11-24 01:55 UTC by TheRyeGuyWhoWillNowDie

Alright so THIS WILL CRASH UNLESS: take test.tscn from maps and put it into /home/<YOUR HOME>/.local/share/opensuspect/maps/servermap.tscn

2020-11-26 19:23 UTC, TheSecondReal0 requested changes
I haven't tested it yet, but looking at the code:
* A better name than "dlman" for the map distributor would be nice
* There is an unused variable introduced in network.gd, please remove it

This PR also seems to add dying for some reason, these features should have separate requests.

2020-11-27 04:08 UTC, TheSecondReal0 requested changes, later dismissed
Thanks for removing dying from this PR, there is still an unused variable, "rawmap," in network.gd and the name of the distributor could be changed to something else, like "dlmanager" or "modmanager" or something. "Modmanager" is probably better, since we'll need that in the future anyways

2020-11-27 05:17 UTC, vincens2005 approved these changes
Looks good!

2020-11-27 05:20 UTC, merged

2020-11-27 08:54 UTC, vainiovano reviewed
Please change the map system. This system doesn't work properly.

2020-11-27 08:54 UTC, vainiovano commented on src/assets/autoload/dlman.gd
> +		map.open("res://assets/maps/test/test.tscn", File.READ)
Send the server's current map instead of the contents of `maps/servermap.tscn`

2020-11-27 08:54 UTC, vainiovano commented on src/assets/autoload/dlman.gd
> +	localmap.open("user://maps/currentmap.tscn", File.WRITE)
If you want to cache the maps to files, you should put their hashes in the file names. For example, Teeworlds puts both the name and hash of the map to the filename.

2020-11-27 08:54 UTC, vainiovano commented on src/assets/autoload/network.gd
> +var rawmap
unused variable

2020-11-27 08:54 UTC, vainiovano commented on src/assets/autoload/network.gd
> +
please put code style changes in another PR

2020-11-27 08:54 UTC, vainiovano commented on src/assets/autoload/playermanager.gd
> +signal host_kill
unused signal

2020-11-27 08:54 UTC, vainiovano commented on src/assets/main/maps.gd
> +var maps: Dictionary = {"lobby": {"dir": preload("res://assets/maps/lobby/lobby.tscn")}, "test": {"dir": load("user://maps/currentmap.tscn")}}
The map needs to be loaded after it has been downloaded. This won't work.

2020-11-27 08:54 UTC, vainiovano commented on src/assets/player/player.gd
> +	PlayerManager.connect("host_kill",self,"on_host_kill")
unused signal

2020-11-27 08:54 UTC, vainiovano commented on src/assets/player/player.gd
> -
again, please put code style changes in another PR

2020-11-27 08:54 UTC, vainiovano commented on src/assets/player/player.tscn
> +
This sprite doesn't work and causes errors.