Killing and reloading (#221)
opensuspect/opensuspect-legacy pull request #229
Opened 2020-12-02 05:51 UTC by jngo102

- Re-implemented red kill outline when near other players as an infiltrator
- Replaced placeholder kill `Sprite` with custom kill and reload `TextureButtons`
- Added `Node2D` named `DeathHandler` which handles player deaths
- Migrated animations to use an `AnimationTree` for more powerful animation blending
- Execute and sync deaths across the network

2020-12-02 06:28 UTC, TheSecondReal0 requested changes
I've made a few review comments, they're mostly trying to keep the codebase as clean as possible. None of them really effect functionality. I tested this in editor and exported, everything works perfectly!

One thing that isn't in the comments is that I would like you to organize the texture files inside ```assets/ui/hud/infiltrator_hud```. This basically means putting them into a folder named "textures" or something inside ```assets/ui/hud/infiltrator_hud```.

All in all, this is a great PR and a giant leap towards alpha!

2020-12-02 06:28 UTC, TheSecondReal0 commented on src/assets/autoload/network.gd
> +func get_rpc_id_from_player_name(player_name: String) -> int:
I don't know if there's a specific reason for crawling the scene tree, but using the ```names``` dict in network.gd would be much easier and cleaner.

Additionally, in other areas of the game RPC IDs are referred to as network IDs. Please change this function name for the sake of consistency.

2020-12-02 06:28 UTC, TheSecondReal0 commented on src/assets/main/main.gd
> +	for player_id in players.keys():
Could add a check here just to make sure the function is running on the server, something like this:
```gdscript
    if not get_tree().is_network_server():
        return
```

2020-12-02 06:28 UTC, TheSecondReal0 commented on src/assets/main/main.gd
> +remote func player_killed(killer_id: int, killed_player_id: int) -> void:
Switch ```remote``` for ```puppet```, this guarantees the function can only be called remotely by the server

2020-12-02 06:28 UTC, TheSecondReal0 commented on src/assets/player/death_handler.gd
> +	var killer: KinematicBody2D = main.players[killer_id]
There's probably a cleaner way to get the list of player nodes, perhaps by storing them in PlayerManager when they are created. This is not a necessary change for merging, but highly recommended.

2020-12-02 06:28 UTC, TheSecondReal0 commented on src/assets/player/infiltrator.gd
> +	ui_controller.open_menu("killui", {"linked_node": self, "rect_position": kill_ui_position}, true)
It seems that you're trying to put the buttons in a set place in the corner of the screen, I think using anchors in the killui scene would be a better solution. Setting all margins to 0 with the top and left anchors to .75 along with bottom and right anchors to 1 should work.

2020-12-02 06:28 UTC, TheSecondReal0 commented on src/assets/player/viewport_texture_target.gd
> +	set_material(material.duplicate())
You might be encountering a weird bug, but I think this is what the ```local_to_scene``` resource setting is for.

2020-12-02 07:17 UTC, jngo102 commented on src/assets/autoload/network.gd
> +func get_rpc_id_from_player_name(player_name: String) -> int:
I should've been more clear about this method's description, but it actually gets the network ID of the player from the name of the player node on the client side, i.e. the KinematicBody2D, not the player's entered name.

2020-12-02 23:25 UTC, TheSecondReal0 commented on src/assets/autoload/network.gd
> +func get_rpc_id_from_player_name(player_name: String) -> int:
OK, looking at the code it looks like the name stored in network.gd should be the same as the name of the player node, but this is more flexible and would survive if we changed that later on. 

One thing I would suggest is moving this out of network.gd, since it doesn't really belong there. I'm not quite sure where to put it if you plan on using this function from a lot of places, but it could just be in the script that calls it. It's your choice to make this change.

2020-12-02 23:38 UTC, TheSecondReal0 submitted a review, later dismissed
Everything looks good! I've replied to one of the comments you made about moving get_network_id_from_player_node_name() to somewhere else. Unless you plan on using this function from a lot of places, I think you could move it into main.gd. It's completely up to you to merge it how it is or to move the function.

2020-12-03 03:33 UTC, TheSecondReal0 approved these changes
Tested everything, code is clean, overall great PR, approved!

2020-12-03 03:35 UTC, merged