Win condition plumbing + majority victory win condition implemented
opensuspect/opensuspect-legacy pull request #245
Opened 2020-12-06 02:16 UTC by nicemicro

Based on @TheRyeGuyWhoWillNowDie 's original idea, I have separated functionality related to win conditions into separate functions.
The elimination victory / gaining majority victory condition has been implemented in this framework in a flexible way.
It currently doesn't include victory scenes, only instant transition back to lobby.

2020-12-06 03:37 UTC, TheSecondReal0 requested changes
There's a bug when the elimination victory is triggered, the last person who's killed is still dead/dying on the impostor client and the murdered client in the lobby. It works perfectly for every other client though.

2020-12-06 04:43 UTC, nicemicro commented
> There's a bug when the elimination victory is triggered, the last person who's killed is still dead/dying on the impostor client and the murdered client in the lobby. It works perfectly for every other client though.

That is true, I have no idea why though, so I request assistance..

2020-12-06 14:23 UTC, nicemicro commented
Thanks for pointing me in the good direction @TheSecondReal0 and for @zapzoop0099  for the help with the networking code.
The bug does not exist anymore, as the checks have been moved to a better place.
Ready for re-review.

2020-12-06 14:50 UTC, vainiovano commented on src/assets/main/main.gd
> +
Is the returned id always equal to `Network.myID` or am I missing something?

2020-12-06 14:50 UTC, vainiovano commented on src/assets/main/main.gd
> +				# Can't RPC on self
RPCing self is possible when using `sync` versions of functions (`remotesync`, `mastersync`, `puppetsync`) (see https://github.com/godotengine/godot/pull/28783)

2020-12-06 23:13 UTC, nicemicro commented on src/assets/main/main.gd
> +
I've seen the main player object being returned similarly in `playermanager.gd` 's `get_main_player()` function.
The only time it wouldn't equal to `Network.myID` or equally the return value of `Network.get_my_id()` would be when run on a dedicated server with no main player.
But as I see I haven't checked for that possibility on the victory / defeat screen selection, so I'm gonna do that.

2020-12-06 23:13 UTC, nicemicro commented on src/assets/main/main.gd
> +				# Can't RPC on self
Fixing, and also doing the same for `player_killed` function

2020-12-07 01:02 UTC, jngo102 approved these changes
Encountered no issues during testing.

2020-12-07 01:10 UTC, TheSecondReal0 approved these changes

2020-12-07 12:48 UTC, merged