Items and inventory (#194)
opensuspect/opensuspect-legacy pull request #246
Opened 2020-12-06 04:02 UTC by jngo102

- Implemented picking up and dropping items, synced over the network
- Modified MapManager and base map scene

2020-12-06 06:36 UTC, vainiovano reviewed
Handling item position syncing like this can result in inexact item positions if the server sends player position updates at a lower rate.

2020-12-06 06:36 UTC, vainiovano commented on src/assets/player/item_handler.gd
> +		player.get_node("Infiltrator").enable_killing(true)
this doesn't work when killing a player that doesn't hold an item (the item is Nil)

2020-12-06 06:36 UTC, vainiovano commented on src/assets/main/main.gd
> +		rpc_id(1, "player_picked_up_item", item_path, Network.get_my_id())
using `remotesync` and just rpcing the server could also work

2020-12-06 06:36 UTC, vainiovano commented on src/assets/main/main.gd
> +remote func player_picked_up_item(item_path: String, id: int) -> void:
you could probably use `get_rpc_sender_id` for these functions if they were always called using rpcs

2020-12-06 06:36 UTC, vainiovano commented on src/assets/main/maps.gd
> +	var map_path: String = Helpers.find_file(new_map_name + ".tscn", maps_path)
map file names could also contain a hash of the map to prevent name collisions

2020-12-07 00:13 UTC, jngo102 commented on src/assets/player/item_handler.gd
> +		player.get_node("Infiltrator").enable_killing(true)
Added null check

2020-12-07 00:13 UTC, jngo102 commented on src/assets/main/main.gd
> +remote func player_picked_up_item(item_path: String, id: int) -> void:
Replaced `Network.get_my_id()` with `get_rpc_sender_id()`

2020-12-07 00:13 UTC, jngo102 commented on src/assets/main/main.gd
> +		rpc_id(1, "player_picked_up_item", item_path, Network.get_my_id())
Changed to `remotesync`

2020-12-07 20:08 UTC, TheRyeGuyWhoWillNowDie approved these changes
good

2020-12-08 00:11 UTC, TheSecondReal0 requested changes
The character is invisible in the lobby and the role screen crashes the game. It crashes on line 7 of ```item_handler.gd```, which is ```onready var item_pickup_range: Area2D = player.get_node("ItemPickupRange")```. The crash is unique to the role screen, as I can disable it and avoid the crash. The character is still invisible in the lobby. For some reason if I click continue through the error, the character is shown with the correct customization on the role screen. The crash repeatedly happens on each continue when the role screen should be shown.

The crash generally seems to be caused by the item handler not being able to grab the player node correctly. Switching ```get_owner()``` to ```get_parent()``` in ```onready var player: Player = get_parent()``` in ```item_handler.gd``` revealed that it's getting set to a Node2D instead of a Player class, this leads me to believe that the item handler script is being loaded somewhere incorrectly.

2020-12-08 00:11 UTC, TheSecondReal0 commented on src/assets/main/maps.gd
> +	print("loading map: ", new_map_name)
It should print "loading map" before the map is loaded, that way it's more useful for debugging.

2020-12-08 00:49 UTC, closed without merging