Items pick and drop functionality
opensuspect/opensuspect-legacy pull request #247
Opened 2020-12-06 07:30 UTC by zapzoop0099

This PR gives the player ability to pick and drop items 

**Features:**

- Player can pick items and drop it and this sync over network

- If the item is picked by an infiltrator killing is disabled

- Items will hover in air when not picked

**This pr doesn't include:-**

- Items related to tasks

- Yellow shader over the items when get close to it

- Any type of asset(It have just a small box as placeholder for item prop )

The map already contained some instanced scene of items so when it get reviewed i will remove them at last
It also doesn't any include good comments :( but if it stays here for long i will push them
Please also refer to pr #246  and merge the best one.

2020-12-07 00:49 UTC, jngo102 requested changes

2020-12-07 00:49 UTC, jngo102 commented on src/assets/main/main.gd
> +	if Input.is_action_just_pressed("ui_pick"):
Putting an `Input.is_action_just_pressed` in `_input` doesn't make use of `event`.
Try using `event.is_action_pressed` instead.

2020-12-07 00:49 UTC, jngo102 commented on src/assets/main/main.gd
> +var keystroke:int
Is `keystroke` ever used? What's its purpose?

2020-12-07 00:49 UTC, jngo102 commented on src/assets/main/main.gd
> +func enable_killing(id):
I'm not sure the expensive tree parsing in `enable_killing` and `disable_killing` are necessary here when you could just use
```
if players[id].has_node("Infiltrator"):
    players[id].get_node("Infiltrator").enable_killing([true/false])
```

2020-12-12 02:38 UTC, zapzoop0099 commented
Didn't match with community standards

2020-12-12 02:38 UTC, closed without merging