Improved lobby scenery
opensuspect/opensuspect-legacy pull request #250
Opened 2020-12-07 20:57 UTC by jngo102

- Random spawning of scenery objects
- Implemented object pooling in a class

2020-12-07 23:52 UTC, TheSecondReal0 requested changes
There's one small change to a function name I'd like you to make but other than that everything looks good! The code looks good and it works perfectly!

2020-12-07 23:52 UTC, TheSecondReal0 commented on src/assets/autoload/helpers.gd
> +func choose(array: Array):
Maybe change this function name to ```pick_random()```?

2020-12-08 03:53 UTC, jngo102 commented on src/assets/autoload/helpers.gd
> +func choose(array: Array):
Changed

2020-12-08 06:21 UTC, TheSecondReal0 approved these changes
Code is solid, works perfectly, ready to merge!

2020-12-08 06:21 UTC, merged