Items and inventory (#194)
opensuspect/opensuspect-legacy pull request #254
Opened 2020-12-08 03:48 UTC by jngo102

- Pick up and drop items with "E" or by clicking on them
- Modified MapManager for easier access to items in maps
- Fixed bugs caused by merging updated main into branch

2020-12-08 17:47 UTC, vainiovano requested changes, later dismissed

2020-12-08 17:47 UTC, vainiovano commented on src/assets/main/main.gd
> +	rpc_id(1, "player_dropped_item")
these functions shouldn't be `remotesync` if they are only called locally

2020-12-08 17:47 UTC, vainiovano commented on src/assets/main/main.gd
> +	"""Called by the server; RPCs all clients to have a player pick up an item."""
"Called by the server" means that the function is rpc'd by the server and executed by the clients in https://github.com/opensuspect/opensuspect/blob/2ff9d8997099a885bceb9445f1e5963c69d1e439/src/assets/main/main.gd#L210-L213

I think that saying "called by client/server" is a bit unclear because it can mean multiple things. At least its usage should be consistent.

2020-12-08 17:55 UTC, TheSecondReal0 commented on src/project.godot
>  "language": "GDScript",
Add a line with ```}, {``` right after line 25, the class isn't being closed correctly so the Godot project can't be opened.

2020-12-09 21:20 UTC, TheRyeGuyWhoWillNowDie requested changes
tell us when it's not broken

2020-12-10 01:05 UTC, TheRyeGuyWhoWillNowDie approved these changes, later dismissed
fixed now cool

2020-12-10 03:50 UTC, jngo102 commented on src/assets/main/main.gd
> +	"""Called by the server; RPCs all clients to have a player pick up an item."""
What do you recommend we call them?

2020-12-10 03:55 UTC, jngo102 commented on src/assets/main/main.gd
> +	rpc_id(1, "player_dropped_item")
Changed.

2020-12-10 13:28 UTC, vainiovano commented on src/assets/main/main.gd
> +	"""Called by the server; RPCs all clients to have a player pick up an item."""
"Runs on the server" sounds good

2020-12-10 15:08 UTC, TheRyeGuyWhoWillNowDie approved these changes, later dismissed
very yes

2020-12-10 16:25 UTC, jngo102 commented on src/assets/main/main.gd
> +	"""Called by the server; RPCs all clients to have a player pick up an item."""
Renamed comments.

2020-12-12 02:26 UTC, TheSecondReal0 approved these changes, later dismissed
Trying to host or join a game on an exported client causes the game to crash. The appearance editor seems bugged as well, it looks like this:

![image](https://user-images.githubusercontent.com/66881186/101970166-d9fa8680-3bf6-11eb-8719-b611dfeea14b.png)

The animations still work, but the textures remain white. Trying to change any setting crashes the game (including skin color). For some reason the crash and editor bug only happen when the game isn't running in debug mode.

Other than this, could you make it so that you don't have to leave and reenter an item's radius to pick it back up?

2020-12-12 02:29 UTC, TheSecondReal0 requested changes
Trying to host or join a game on an exported client causes the game to crash. The appearance editor seems bugged as well, it looks like this:

![appearance-bug](https://user-images.githubusercontent.com/66881186/101970332-c6035480-3bf7-11eb-85da-c332c1bc472d.PNG)

The animations still work, but the textures remain white. Trying to change any setting crashes the game (including skin color). For some reason these issues only occur when the game isn't running in debug mode.

Other than this, could you make it so that you don't have to leave and reenter an item's radius to pick it back up?

2020-12-12 14:28 UTC, nicemicro submitted a review, later dismissed
I have two issues with this implementation at the moment:
1. Items are visible outside of vision range if not carried, and they appear when dropped.
2. Ghosts can pick up items and carry them. Items picked up by ghosts disappear, and reappear when dropped.

2020-12-12 14:36 UTC, nicemicro commented
> The animations still work, but the textures remain white. Trying to change any setting crashes the game (including skin color). For some reason these issues only occur when the game isn't running in debug mode.
By a cursory look it seems to me that the exported stuff doesn't contain the required png files, and also, there used to be a pck file alongside the binary, which doesn't exist in the zip file provided by the CI.
Moreover, the same is true for #261 for example.

2020-12-28 04:38 UTC, TheSecondReal0 requested changes
While the problems with the appearance editor are not caused by this PR, there is a crash that occurs when you try to host or join a game on an exported/non-debug version. I've narrowed it down to being an issue with how maps.gd is finding the map file path. ```Helpers.find_file()``` seems to cause the crash.

Another minor thing is that you can't drop an item and immediately pick it back up, you have to walk far enough away so that the item can re-enter the item radius.

2020-12-28 04:38 UTC, TheSecondReal0 commented on src/assets/main/maps.gd
> +	var map_path: String = Helpers.find_file(new_map_name + ".tscn", maps_path)
Replacing this line with:
```gdscript
var map_path: String = maps_path + new_map_name + "/" + new_map_name + ".tscn"
```
fixes the crash and allows the exported/non-debug version to run correctly. This only works if the folder and the scene have the same name, luckily for us that's already how it is.

2020-12-28 04:43 UTC, TheSecondReal0 commented
from @nicemicro
> By a cursory look it seems to me that the exported stuff doesn't contain the required png files, and also, there used to be a pck file alongside the binary, which doesn't exist in the zip file provided by the CI.
> Moreover, the same is true for #261 for example.

The PCK isn't created because it's set to include it inside the executable

2021-01-25 12:41 UTC, nicemicro commented
This work has been continued in a different PR due to the merge conflicts that arose here.

2021-01-25 12:41 UTC, closed without merging