Despagettified main.gd
opensuspect/opensuspect-legacy pull request #259
Opened 2020-12-10 20:12 UTC by vincens2005

closes #256

2020-12-13 05:45 UTC, nicemicro requested changes, later dismissed
There is a breaking bug. Please investigate.

2020-12-13 05:45 UTC, nicemicro commented on src/assets/main/players.gd
> +	if get_tree().is_network_server():
`Attempt to call function 'is_network_server' in base 'null instance' on a null instance.`
error and the game breaks here when starting a new game.

2020-12-13 05:57 UTC, TheSecondReal0 requested changes, later dismissed
Could you try to move all of player management into players.gd (killing and movement is still handled in main.gd)

2020-12-13 05:57 UTC, TheSecondReal0 commented on src/assets/main/players.gd
> +	$".".add_child(newPlayer)
```$".".``` is unnecessary

2020-12-13 06:53 UTC, nicemicro commented
> Could you try to move all of player management into players.gd (killing and movement is still handled in main.gd)

or maybe playermanager.gd, but that's up for a debate.

2021-01-04 13:31 UTC, nicemicro submitted a review, later dismissed
No obvious new bugs introduced, the code looks clean, approved.

2021-01-04 20:42 UTC, TheSecondReal0 requested changes, later dismissed
It could use a few minor changes, mostly just offloading a few RPCs and variables to players.gd for readability and easy debugging

2021-01-04 20:42 UTC, TheSecondReal0 commented on src/assets/main/main.gd
> +		$players.rpc("createPlayers", Network.get_player_names(), player_spawn_points)
Ideally this script would be calling ```createPlayers()``` on the player script and it would handle the rpc to make debugging easier. Or the player script could connect to the state_changed_priority signal and call ```createPlayers()``` itself.

This also applies for lines 32, 57, and 60

2021-01-04 20:42 UTC, TheSecondReal0 commented on src/assets/main/players.gd
> +	if get_parent().players.keys().has(id):
Why not just move the ```players``` var (along with other player related variables like ```player_scene```) into players.gd? An easy way to migrate them is to add a getter in main.gd that points to the related variable in players.gd.

2021-01-07 23:42 UTC, nicemicro approved these changes
Works on my machine, the code quality looks good.

2021-01-08 03:26 UTC, TheSecondReal0 approved these changes
Everything looks good!

2021-01-08 03:28 UTC, merged