Task network sync
opensuspect/opensuspect-legacy pull request #265
Opened 2020-12-17 01:07 UTC by Damjan94

Tasks now sync to the server.

Once #264 is merged, I will correct a few things that I can't do cleanly without that feature(if you wanted to spawn items via a resource, when task is done, it would not work)

2020-12-17 06:12 UTC, TheSecondReal0 requested changes
I haven't been able to test it yet, but I've looked at the code. It looks like most task functions require a network/player id as an input, how does this work for global tasks? Maybe make them optional inputs?

2020-12-17 06:12 UTC, TheSecondReal0 commented on src/addons/opensusinteraction/resources/interacttask/interacttask.gd
> +var _task_data: Dictionary = {}
What is the rationale for changing this variable's name?

2020-12-25 19:02 UTC, TheSecondReal0 requested changes, later dismissed
I'm not sure why this new code is referring to tasks by their text instead of their ID. I see that IDs are filtered out when sending over the network, but I don't understand why. It seems that you'd want the IDs to be able to reliably refer to tasks?

2020-12-25 19:02 UTC, TheSecondReal0 commented on src/addons/opensusinteraction/resources/interacttask/interacttask.gd
> +func complete_task(	player_id: int = TaskManager.GLOBAL_TASK_ID,
I personally would put ```player_id``` after ```data```, it doesn't really matter though. Maybe you could include the player data inside the task data dict (I think the keys are already generated).

2020-12-25 19:02 UTC, TheSecondReal0 commented on src/assets/autoload/taskgenerators.gd
> +#these generators should generate new data every time they are called
I'm a bit weary about adding a new autoload. It looks like this is mainly generating a starting position for the clockset task (and theoretically other tasks), I think it would be better to try to bake this into the interact task as part of the editor UI.

2020-12-25 19:02 UTC, TheSecondReal0 commented on src/assets/autoload/taskmanager.gd
> +	var keys_to_erase = ["task_id", "task_outputs", "attached_node", "resource"]
I'm not sure why the task ID is getting filtered out, shouldn't you be using it to refer to the task?

2020-12-25 19:02 UTC, TheSecondReal0 commented on src/assets/common/classes/ui/task/controltask.gd
> +	TaskManager.rpc_id(1, 	"complete_task_remote", ui_data["task_text"],
I think we should be using the task ID to refer to tasks, as 2 different tasks could have the same text.

Could you also switch it up so that this calls a function inside the task manager which executes the RPC? Putting it here makes the codebase more confusing.

2020-12-25 21:50 UTC, Damjan94 commented on src/assets/common/classes/ui/task/controltask.gd
> +	TaskManager.rpc_id(1, 	"complete_task_remote", ui_data["task_text"],
yes, I agree that it should be calling a function inside the TaskManager.

2020-12-25 22:03 UTC, Damjan94 commented on src/assets/autoload/taskmanager.gd
> +	var keys_to_erase = ["task_id", "task_outputs", "attached_node", "resource"]
because the task ID needs to be unique, and is most likely different on every game instance.
syncing the task ID between the clients and the server would require more code, so I opted for this approach, since two tasks are rarely going to need to have the same description, and even if they do, one could just append a character, or something...

2020-12-25 22:03 UTC, Damjan94 commented on src/assets/autoload/taskgenerators.gd
> +#these generators should generate new data every time they are called
I don't think bloating anything task related, would be a good idea. because every task would need to generate it's own data, there would be a lot of code(maybe?)
I'm not sure what you mean by baking it into an editor ui...

2020-12-25 22:04 UTC, Damjan94 commented on src/addons/opensusinteraction/resources/interacttask/interacttask.gd
> +func complete_task(	player_id: int = TaskManager.GLOBAL_TASK_ID,
I will look into this

2021-01-12 12:22 UTC, nicemicro approved these changes
Works as intended, no unexpected behavior was observed, the game doesn't work.
Seems to have addressed all issues @TheSecondReal0 had with the previous versions.

2021-01-14 10:42 UTC, merged