Character customization screen refactoring for more custom color selection
opensuspect/opensuspect-legacy pull request #272
Opened 2021-01-03 14:40 UTC by nicemicro

In this PR I have

1. added a new scene which uses PNG bitmaps for color selection,
2. modified the character sprites to be compatible with the shaders / color customization,
3. refactored the whole appearance editor screen to be able to include the new options,
4. added a randomize button for random character generation.

I will make this PR live as soon as I have finalized the color maps (current ones are provisional).

2021-01-08 00:39 UTC, vincens2005 submitted a review, later dismissed
Looks good, the only think I think we might want to change in the future is that the skin color picker is missing a lot of shades. Other than that, everything looks good.

2021-01-08 03:44 UTC, TheSecondReal0 requested changes, later dismissed
On an exported client the appearance editor doesn't seem to find the correct files, and you end up switching between files in ```src``` instead of outfit textures. My best guess is that it's something in ```getFilePaths()``` on line 69 (nice) in appearancemanager.gd. That function uses .png instead of .png.import like ```partFiles()```

2021-01-09 03:20 UTC, nicemicro commented
> On an exported client the appearance editor doesn't seem to find the correct files, and you end up switching between files in `src` instead of outfit textures. My best guess is that it's something in `getFilePaths()` on line 69 (nice) in appearancemanager.gd. That function uses .png instead of .png.import like `partFiles()`

The only thing didn't work on an exported project if I export myself on my PC, was the color maps due to loading using Image.load() function that is documented to break on exported projects.
I corrected that error. I think the export issue might be a CI setup issue.

2021-01-09 09:04 UTC, nicemicro commented
> On an exported client the appearance editor doesn't seem to find the correct files, and you end up switching between files in `src` instead of outfit textures. My best guess is that it's something in `getFilePaths()` on line 69 (nice) in appearancemanager.gd. That function uses .png instead of .png.import like `partFiles()`

Couldn't fix the issue, but found something that's borked during export, and fixed that. Maybe that issue could get its own PR.

2021-01-12 17:29 UTC, Damjan94 approved these changes
all seems to be working fine, I left comments on the old code, I leave it up to you if you think it should be changed in this PR.

2021-01-12 17:29 UTC, Damjan94 commented on src/assets/autoload/appearancemanager.gd
>  master func queryCustomization(id: int) -> void:
this should be just a normal function(without master keyword)
line 199 (func sendCustomizationToServer()) should have puppet keyword instead
204 (func receiveCustomizationFromClient) should have master keyword
228 (func receiveBulkCustomization) should be puppet too.

I know that this isn't your code, but I think these changes should be made somewhere

2021-01-12 17:42 UTC, nicemicro commented on src/assets/autoload/appearancemanager.gd
>  master func queryCustomization(id: int) -> void:
No, actually this is my code, so I'll take a look and change it.

2021-01-12 22:32 UTC, Damjan94 requested changes

2021-01-12 22:32 UTC, Damjan94 commented on src/assets/autoload/appearancemanager.gd
> +		color_map = Image.new()
this assignment is redundant

2021-01-12 22:32 UTC, Damjan94 commented on src/assets/ui/submenus/appearance_editor/color_selector.gd
> +	coord.x = int(x_rel / 1.0 / AppearanceManager.COLOR_XY * max_x)
what's the purpose of the '1.0' here?(please explain like you're explaining to someone who has skipped all of the math classes xD )

2021-01-12 22:32 UTC, Damjan94 commented on src/assets/ui/submenus/appearance_editor/color_selector.gd
> +			preview_border.rect_position.y = -40
I feel it's a bit trippy how the box jumps to the top. I think it would be fine if it were to be drawn on top of the elements below it. But that's just my opinion. Leave it as is if no one else agrees with me, or if it's too much work to get it any other way.

2021-01-12 22:48 UTC, vincens2005 commented on src/assets/ui/submenus/appearance_editor/color_selector.gd
> +	coord.x = int(x_rel / 1.0 / AppearanceManager.COLOR_XY * max_x)
It shouldn't make a difference, / 1.0 should be removed

2021-01-12 23:55 UTC, nicemicro commented on src/assets/ui/submenus/appearance_editor/color_selector.gd
> +	coord.x = int(x_rel / 1.0 / AppearanceManager.COLOR_XY * max_x)
it is to implicitly cast x_rel to float, so the division doesn't get automatically rounded down to zero while keeping the order of the operations so it is easy to see what these lines do.

2021-01-12 23:57 UTC, nicemicro commented on src/assets/ui/submenus/appearance_editor/color_selector.gd
> +			preview_border.rect_position.y = -40
In the current form, due to the container used, the things below appear "on top of" the things above.
As in, if the color preview of the skintone goes down, it will go behind the color map of the hair color, which is worse, than this trippyness.

2021-01-13 00:32 UTC, nicemicro commented on src/assets/autoload/appearancemanager.gd
> +		color_map = Image.new()
removed.

2021-01-13 00:33 UTC, nicemicro commented on src/assets/ui/submenus/appearance_editor/color_selector.gd
> +	coord.x = int(x_rel / 1.0 / AppearanceManager.COLOR_XY * max_x)
actually managed to fix it with the float keyword

2021-01-13 00:37 UTC, Damjan94 commented on src/assets/ui/submenus/appearance_editor/color_selector.gd
> +			preview_border.rect_position.y = -40
ok, fair enough.

2021-01-13 00:40 UTC, Damjan94 approved these changes

2021-01-13 21:01 UTC, Damjan94 approved these changes
approved again, after joining opensuspect team

2021-01-15 14:11 UTC, merged