Items and inventory based on #254
opensuspect/opensuspect-legacy pull request #279
Opened 2021-01-10 08:55 UTC by nicemicro

It has been a long time since #254 has been PR'd, so I tried to merge the main branch into it, so we can proceed.

2021-01-22 12:17 UTC, zapzoop0099 commented
The game is acutally working fine and debug messages are also nice. But i have found a loophole in the system pretty easy to be fixed but important.Actually using this loophole player can pick up or to be more precise drag 2 items in one place.
How to reproduce:-

- Hold any item 
- Go near to another item
- And start spamming the "E" key and run in any direction 

Using this a player can easily drag two items at once place.This was also present in the Base PR. It can be easily fixed by changing the rate at which the player can pick up item

2021-01-24 09:26 UTC, nicemicro commented
Multiple things are addressed, including @zapzoop0099 's concerns for the abusability of repeated dast pick up and drop of items.
The item highlighting has been revamped, now the item you can pick up with the "E" key is highlighted in green, others that you can select by the mouse are highlighted in yellow.

2021-01-24 13:17 UTC, Damjan94 requested changes
apart from the merge conflict,
the infiltrator can kill, pick up an item, reload(while holding the item), and kill again(while holding the item)

2021-01-24 13:19 UTC, nicemicro commented
> apart from the merge conflict,
> the infiltrator can kill, pick up an item, reload(while holding the item), and kill again(while holding the item)

Thanks for the in depth testing, guess this will require a little more in-depth rewrite of some parts, I'll get be back to it as soon as possible.

2021-01-25 14:13 UTC, Damjan94 commented on src/assets/autoload/helpers.gd
> +	assert(directory.open(start_path) == OK)
I still think that this should be replaced with
```
if directory.open(start_path) != OK:
    assert(false)
    return
```
as the asserts get removed in the release build

2021-01-25 14:13 UTC, Damjan94 commented on src/assets/autoload/helpers.gd
>  	assert(directory.open(path) == OK)
same here, asserts won't work in  release builds

2021-01-25 14:13 UTC, Damjan94 commented on src/assets/main/main.gd
> +var intruders = 0 # NiceMicro's question: is this value ever referenced anywhere?
no, according to `grep -r "intruders" ./`

2021-01-25 14:13 UTC, Damjan94 commented on src/assets/main/players.gd
> +	rpc("pick_up_item", id, item_path)
Could you write a TODO, to check if the player trying to pick up an item is actually close enough to the item?

2021-01-25 14:13 UTC, Damjan94 commented on src/assets/player/item_handler.gd
> +func _process(delta: float) -> void:
should this then be removed?

2021-01-26 15:40 UTC, nicemicro commented on src/assets/autoload/helpers.gd
> +	assert(directory.open(start_path) == OK)
The use of any code that just searches for files in directories will be removed in the future.

2021-01-26 15:40 UTC, nicemicro commented on src/assets/autoload/helpers.gd
>  	assert(directory.open(path) == OK)
Same answer.

2021-01-26 15:41 UTC, nicemicro commented on src/assets/main/main.gd
> +var intruders = 0 # NiceMicro's question: is this value ever referenced anywhere?
Probably we'll have to revamp the roles system to make it a little more flexible with different teams and roles, so I'd leave dealing with this for that time.

2021-01-26 15:43 UTC, nicemicro commented on src/assets/main/players.gd
> +	rpc("pick_up_item", id, item_path)
Let's make an issue instead to include more server-side verification of actions instead of just adding a few TODO-s here and there in the code..

2021-01-26 15:45 UTC, nicemicro commented on src/assets/player/item_handler.gd
> +func _process(delta: float) -> void:
I left it in for the time being, because we might use it for further improvements of the system.

2021-01-27 00:01 UTC, Damjan94 requested changes

2021-01-27 00:01 UTC, Damjan94 commented on src/assets/player/infiltrator.gd
> +const max_shots: int = 1
The `infiltrator_hud.gd` catches the first `"kill"` signal, and disables the kill button, and enables the reload button.
when this value is set to more than 1, this makes it so that after the first reload the infiltrator is able to fire for one more time. After that the `infiltrator_hud.gd` switches to the reload button, but infiltrator is unable to reload(`reload_only_empty == true`)

The simplest fix I can think of is to decrement the `_shots_left` before emitting the `"kill"` signal, and passing that value in the signal. Then in `infiltrator_hud.gd` just return if the value is >0...

2021-01-27 13:27 UTC, Damjan94 approved these changes

2021-01-28 00:16 UTC, merged