Fixes the rolescreen crash(#271)
opensuspect/opensuspect-legacy pull request #286
Opened 2021-01-15 18:46 UTC by Damjan94

Makes the rolescreen go thrugh the ui manager

2021-01-16 00:27 UTC, nicemicro requested changes
TLDR: the instance that was server first, when tries to join a game hosted by an other instance, breaks on rolescreen.

I can still get a crash on the rolescreen:
- run OpenSuspect in 4 instances
- create a game on instance 1
- join all other clients, start, back to lobby, leave the game.
- create a game on instance 1
- join all other clients, start -> rolescreen works, back to lobby, leave the game.
- create a game on instance 2
- join all other clients, start -> rolescreen breaks on instance 1.

The crash happens in rolescreen.gd:101 at function _create_info, with an` invalid get index on base 'Dictionary'`. For some reason, the player_sprite_collection didn't get populated properly.

2021-01-22 14:30 UTC, TheSecondReal0 commented
This sounds like it has something to do with network info (peers + names) not being cleared when you return to the main menu. Maybe adding a cleanup phase to network.gd would help?

2021-01-24 01:03 UTC, nicemicro requested changes
If I correct the abovementioned spaces to a tab character, the game works.

2021-01-24 01:03 UTC, nicemicro commented on src/assets/ui/hud/defaulthud/rolescreen/rolescreen.gd
> +  """
That three quotation marks with the spaces in front of them instead of a tab makes Godot rage quit if running the game from the editor.
Moreover, I don't think it's good form to have the TODO in a string like this, let's just make it a normal comment with #

2021-01-24 11:08 UTC, Damjan94 commented on src/assets/ui/hud/defaulthud/rolescreen/rolescreen.gd
> +  """
I resolved the merge conflict here, on github so I didn't notice the spacing...
good thing you caught that :)

2021-01-26 11:11 UTC, nicemicro submitted a review, later dismissed
Good, works perfectly, code is clean.

2021-01-29 13:56 UTC, nicemicro approved these changes

2021-01-29 21:08 UTC, merged