Custom task logic via extending InteractTask
opensuspect/opensuspect-legacy pull request #300
Opened 2021-02-13 03:42 UTC by TheSecondReal0

* Added a bunch of virtual functions meant to be overridden to interacttask.gd
* Added functions in both interacttask.gd and the task manager to facilitate syncing task resource scripts (they are basically proxies for rpc and rset)
* Ported the clockset task connected to the standbutton to use a script extending InteractTask for logic (tasks are still completed via the UI class)

I'll type up some documentation at some point, to see an example of using the InteractTask resource for logic look at the clockset task (resource script is at ```res://assets/ui/tasks/clockset/clocksetinteracttask.gd```)

TODO:
* Have task resources tell the task manager when they are completed
* Add some security to task resource rpc and rset, currently any peer can do whatever they want
* Maybe change task manager to use task IDs instead of task_info dicts, @Damjan94 what is your opinion on this?

2021-02-13 05:59 UTC, nicemicro reviewed
Quite cool!

2021-02-13 05:59 UTC, nicemicro commented on src/addons/opensusinteraction/resources/interacttask/interacttask.gd
> +	callv(function, args)
couldn't it be done so that task resources can only RPC the server, and can only accept RPCs from the server?

2021-02-13 05:59 UTC, nicemicro commented on src/addons/opensusinteraction/resources/interacttask/interacttask.gd
> +	callv(function, args)
sholdn't it be enough for the task resource to only ever RPC the server, and then the server only validates the data and then receives the data only from the server?

2021-02-13 07:01 UTC, TheSecondReal0 commented on src/addons/opensusinteraction/resources/interacttask/interacttask.gd
> +	callv(function, args)
Yeah, it could be done that way. I set it up like this so each task can fully customize their networking stuff 😃

2021-02-19 13:24 UTC, nicemicro requested changes
Besides the questions with respect to the code, the following bugs need to be addressed:
1. The task list fails to color the completed tasks green.
2. When the clockset task (standbutton) is completed, the text showing the time next to the standbutton is only changed on the other players' map if they stand on the button.
3. On the interact button version, the text is only updated if the other player goes there and clicks on the task test button.

2. and 3. should be addressed that every time there is an update broadcasted to all clients, the script should update the text.

2021-02-19 13:24 UTC, nicemicro commented on src/assets/ui/tasks/clockset/clockset.gd
> +	return TaskManager.get_task_resource(ui_data[TaskManager.TASK_ID_KEY])
I am trying to figure out where is the ui_data dictionary gets populated with the correct task ID, but I can't figure it out. Please enlighten me.

2021-02-19 13:24 UTC, nicemicro commented on src/assets/ui/tasks/clockset/clocksetinteracttask.tres
> +is_task_global = true
What is the purpose of this file?
I saw that the map features use the `interactpointclockset.tres` and `standbuttonclockeset.tres` resources as Interact Resource in their respective points, however those resources are linked to `clocksetinteracttask.gd` as their script. However, this tres file seems to be referenced nowhere.

2021-02-19 16:50 UTC, TheSecondReal0 commented on src/assets/ui/tasks/clockset/clockset.gd
> +	return TaskManager.get_task_resource(ui_data[TaskManager.TASK_ID_KEY])
It is updated by uicontroller.gd right before it's opened

2021-02-19 16:52 UTC, TheSecondReal0 commented on src/assets/ui/tasks/clockset/clocksetinteracttask.tres
> +is_task_global = true
It was mostly for testing, and so I could make a copy of it to make the resource files used in the test map. Just putting that resource into the map either did really weird stuff (like adding a copy of the script inside test.tres) or I couldn't give them unique task text (despite them both being local to scene).

2021-02-19 17:00 UTC, TheSecondReal0 commented
I think bugs 2 and 3 are caused by incorrect syncing of the clockset task, which would explain why it works perfectly if you complete the task on the host. I'll fix the syncing issues

2021-02-19 18:06 UTC, TheSecondReal0 commented
Bugs 2 and 3 were actually caused by ```attempt_complete_task()``` being called normally instead of via RPC

2021-02-20 03:22 UTC, nicemicro submitted a review, later dismissed

2021-02-20 14:27 UTC, Damjan94 submitted a review, later dismissed
If you make any task not global
![image](https://user-images.githubusercontent.com/20781278/108598790-0f0e1c80-7390-11eb-9b22-023eb0125773.png)
and try to complete it, the game crashes...

2021-02-21 05:38 UTC, nicemicro submitted a review, later dismissed
I have found the following issues, please take a look.

1. Non-global tasks have the same final state (clock hands) and the states ("digital" clock) are synced through clients
2. Attempting to finish a non-global task on a client when the server is ran from the editor, results in an assertion error on the server in taskinfo.gd _on_task_completed() function, line 30
3. Attempting to finish a non-global task on a client when the client is ran from the editor doesn't cause any issues.
4. Attempting to finish a non-global task on a client not ran from the editor causes an error on a client that's ran from the editor in interacttask.gd transition() function, line 241 "Invalid get index (on base: Dictionary).
5. When all clients and the server are ran not from the editor, issues 2, 3 and 4 are not reproduced, however issue 1 causes the behavior that when someone finishes their clockset task, the second person who has the same personal task finishes the task immediately on opening it due to the state syncing.
6. If two players are attending to the same global task, and one changes the state, closes the window, the second player's display changes which is expected behavior. However, if one of the players is killed while their task window is open, they can still change the task state and when closing the window it gets synced across the network.

2021-02-21 05:38 UTC, nicemicro commented on src/addons/opensusinteraction/resources/interacttask/interacttask.gd
> +	var old_state = task_data_player[player_id]["state"]
the place where one of the weird bugs appear

2021-02-21 05:54 UTC, TheSecondReal0 commented
To respond to your review @nicemicro
1. This is because I wrote the clockset logic with only global tasks in mind, I'll alter it accordingly
2. That assertion should be removed, as it will trigger an error when the game is functioning correctly
3. This seems to just be a note
4. This might be caused by some weird syncing, I'll take a closer look in the future
5. This is also because the clockset logic is only written to be a global task, like 1
6. This should probably fall under another PR, since this deals with death behavior (there should probably be a signal from PlayerManager which the UI system would use to close UIs). There could also be a default check added in ```sync_task()``` for whether or not the main player is alive

2021-02-23 12:24 UTC, nicemicro requested changes
I found the following issue:
1. The global clockset task have different different goal times on each clients.
2. When the first player opens the task window and closes it, the goal time gets set to the goal of the first player to everyone else.
3. The text next to the stand button shows the same time for everyone, but it only matches with the time on the client that was the last to join the party.
4. The text next to the stand button is only updated in case of successful completion of the task. Is it possible to update the related map item the same way when the task UI is updated, i.e. every time someone closes the task UI / changes some important parameter, so there could be some indication of the state of a task directly on the map in some cases?

2021-02-24 19:53 UTC, TheSecondReal0 commented
* Addressed issues 1, 2, and I think 3 by adding player data syncing (sync occurs when the server sends task assignments)
* To address issue 4, I made it so that whenever times are synced on global clockset tasks it will update the map text, and personal tasks will update map text if it's assigned to you

2021-02-25 13:03 UTC, nicemicro approved these changes
This! Is! Approved!

2021-02-26 12:46 UTC, merged